/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-04-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class FarolPld {
    @AuraEnabled public String id_analise {get;set;}
    @AuraEnabled public String risco {get;set;}
    @AuraEnabled public String situacao_processamento {get;set;}
}